### ISSUE TITLE
rc1 update should be removed, s10+ is always crashing.

### ISSUE THREAD

**Issue by FarisZR** [whatawurst/android_device_samsung_beyond2lte#21]
hello 
i prefer to use github because xda is just bad for following up on issues.

the RC1 update is disastrous its really bad. and should be removed at least for the s10+
i am back on beta 3 which much better and way more stable.
the device cant be up for more than 30min without crashing.
what i mean by crashing is, reaching for the device putting my fingreprint and black screen, the device doesn't turn on
i have to force restart it.
this happened more than 8 times today.
and it got into a boot loop three times in a single day
the screen dims on the linage logo and the system doest boot.
imo the rc1 update should be removed

galaxy s10+
twrp recovery: 3.4

**Comment by Linux4** [comment]
This was fixed by https://github.com/whatawurst/android_device_samsung_exynos9820-common/commit/4cb54dab94bd7cfd1fb0cb6a4cdd54890dcc4b1b (at least on my S10)
So it should be fixed in the next build

**Comment by cryptomilk** [comment]
rc2 will be released on Monday.

**Comment by cryptomilk** [comment]
Btw. you can just download the file and push it to /vendor/etc/powerhint.json

**Comment by FarisZR** [comment]
> This was fixed by [whatawurst/android_device_samsung_exynos9820-common@4cb54da](https://github.com/whatawurst/android_device_samsung_exynos9820-common/commit/4cb54dab94bd7cfd1fb0cb6a4cdd54890dcc4b1b) (at least on my S10)
> So it should be fixed in the next build

this fixes the reboot issue what about the black screen ?

**Comment by Linux4** [comment]
> > This was fixed by [whatawurst/android_device_samsung_exynos9820-common@4cb54da](https://github.com/whatawurst/android_device_samsung_exynos9820-common/commit/4cb54dab94bd7cfd1fb0cb6a4cdd54890dcc4b1b) (at least on my S10)
> > So it should be fixed in the next build
> 
> this fixes the reboot issue what about the black screen ?

It also fixes that black screen issue on my S10 (its up for over 4h without problems)

**Comment by cryptomilk** [comment]
Closing as fixed.

**Comment by FarisZR** [comment]
can you please add releases to github?
its easier better to follow them here than xda
