### ISSUE TITLE
XDA forum post deleted?, swtich to github for releases and bug reports

### ISSUE THREAD

**Issue by FarisZR** [whatawurst/android_device_samsung_beyond2lte#28]
Hi, after the switch to xenforo, i cant find modpunk's profile neither the forum post.

i think its time to switch to github releases so we can follow the updates easily.

imo the xda forum post should act like an announcement only, and github should be used for releases and bug reporting.

**Comment by cryptomilk** [comment]
They updated to a new version, but e.g. my thread is pointing to an old version:

https://forum.xda-developers.com/t/rom-exynos-lineageos-17-1-for-s10e-s10-s10-v1-1-update-2020-09-11.4076585/

**Comment by FarisZR** [comment]
interesting it doesn't show up in search engine, anyway thanks for the quick reply.

the change log is not pinned though
